# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Convertor' do
  # Comment the next line if you don't want to use dynamic frameworks
  

  # Pods for Convertor
  pod 'XMLCoder'
  pod 'SwiftyXML'
  pod 'xcodeproj', '~> 7.19.0'
  pod 'NSGradientView'
end
